#############################################################################
# Makefile for building: epollServer
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 5? 5 17:33:05 2015
# Project:  epollServer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile epollServer.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -O0 -std=c++0x -mmacosx-version-min=10.7 -stdlib=libc++ -W -Wno-unused-parameter -gdwarf-2 -arch x86_64 $(DEFINES) -g -gdwarf-2 -arch x86_64 $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/unsupported/macx-clang -I. -Isdu -Inewlist -ITransfer -Ideps/tinyxml -Ideps/fd -Ideps -Ideps/curlpp-0.7.3/include -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions//include/python -I/usr/include -I/usr/local/include
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.7 -stdlib=libc++ -arch x86_64
LIBS          = $(SUBLIBS)   -lcurl -lzmq -lpython -L/usr/lib -lboost_thread -lboost_system -lboost_program_options -lboost_python -L/usr/local/lib 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = main.cpp \
		eplnetwork/Mutex.cpp \
		eplnetwork/ServerClientSocket.cpp \
		eplnetwork/Socket.cpp \
		eplnetwork/SocketMgr.cpp \
		eplnetwork/SocketOps.cpp \
		eplnetwork/ThreadPool.cpp 
OBJECTS       = tmp/main.o \
		tmp/Mutex.o \
		tmp/ServerClientSocket.o \
		tmp/Socket.o \
		tmp/SocketMgr.o \
		tmp/SocketOps.o \
		tmp/ThreadPool.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/clang.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		epollServer.pro
QMAKE_TARGET  = epollServer
DESTDIR       = 
TARGET        = epollServer

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: epollServer.pro  /usr/local/Qt4.8/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/clang.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile epollServer.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/clang.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile epollServer.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/epollServer1.0.0 || $(MKDIR) tmp/epollServer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/epollServer1.0.0/ && (cd `dirname tmp/epollServer1.0.0` && $(TAR) epollServer1.0.0.tar epollServer1.0.0 && $(COMPRESS) epollServer1.0.0.tar) && $(MOVE) `dirname tmp/epollServer1.0.0`/epollServer1.0.0.tar.gz . && $(DEL_FILE) -r tmp/epollServer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) epollServer


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

tmp/main.o: main.cpp eplnetwork/ServerClientSocket.h \
		eplnetwork/Network.h \
		eplnetwork/BaseSocket.h \
		eplnetwork/SocketOps.h \
		eplnetwork/Common.h \
		eplnetwork/Singleton.h \
		eplnetwork/ThreadPool.h \
		eplnetwork/Mutex.h \
		eplnetwork/Socket.h \
		eplnetwork/StraightBuffer.h \
		eplnetwork/BaseBuffer.h \
		eplnetwork/SocketMgr.h \
		eplnetwork/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/main.o main.cpp

tmp/Mutex.o: eplnetwork/Mutex.cpp eplnetwork/Mutex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Mutex.o eplnetwork/Mutex.cpp

tmp/ServerClientSocket.o: eplnetwork/ServerClientSocket.cpp eplnetwork/ServerClientSocket.h \
		eplnetwork/Network.h \
		eplnetwork/BaseSocket.h \
		eplnetwork/SocketOps.h \
		eplnetwork/Common.h \
		eplnetwork/Singleton.h \
		eplnetwork/ThreadPool.h \
		eplnetwork/Mutex.h \
		eplnetwork/Socket.h \
		eplnetwork/StraightBuffer.h \
		eplnetwork/BaseBuffer.h \
		eplnetwork/SocketMgr.h \
		eplnetwork/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/ServerClientSocket.o eplnetwork/ServerClientSocket.cpp

tmp/Socket.o: eplnetwork/Socket.cpp eplnetwork/Common.h \
		eplnetwork/Singleton.h \
		eplnetwork/Network.h \
		eplnetwork/BaseSocket.h \
		eplnetwork/SocketOps.h \
		eplnetwork/ThreadPool.h \
		eplnetwork/Mutex.h \
		eplnetwork/Socket.h \
		eplnetwork/StraightBuffer.h \
		eplnetwork/BaseBuffer.h \
		eplnetwork/SocketMgr.h \
		eplnetwork/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Socket.o eplnetwork/Socket.cpp

tmp/SocketMgr.o: eplnetwork/SocketMgr.cpp eplnetwork/Common.h \
		eplnetwork/Singleton.h \
		eplnetwork/Network.h \
		eplnetwork/BaseSocket.h \
		eplnetwork/SocketOps.h \
		eplnetwork/ThreadPool.h \
		eplnetwork/Mutex.h \
		eplnetwork/Socket.h \
		eplnetwork/StraightBuffer.h \
		eplnetwork/BaseBuffer.h \
		eplnetwork/SocketMgr.h \
		eplnetwork/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/SocketMgr.o eplnetwork/SocketMgr.cpp

tmp/SocketOps.o: eplnetwork/SocketOps.cpp eplnetwork/SocketOps.h \
		eplnetwork/Common.h \
		eplnetwork/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/SocketOps.o eplnetwork/SocketOps.cpp

tmp/ThreadPool.o: eplnetwork/ThreadPool.cpp eplnetwork/ThreadPool.h \
		eplnetwork/Mutex.h \
		eplnetwork/Common.h \
		eplnetwork/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/ThreadPool.o eplnetwork/ThreadPool.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

